### ISSUE TITLE
笔记本显示

### ISSUE THREAD

**Issue by L-09** [rmdhnreza/eza.web.id#1]
你好，我拜读了您的博客，请问您的博客是如何实现在15.6寸笔记本电脑上的三栏显示呢，原版的主题只能显示两栏，能告诉我吗，非常感谢🙏

**Comment by rmdhnreza** [comment]
First, edit **sidebar.scss**
https://github.com/rmdhnreza/rmdhnreza.my.id/blob/6a086c34c30e54d45540b99af5fdeacd922a36ae/assets/scss/partials/sidebar.scss#L48-L73

Second, edit **grid.scss**
https://github.com/rmdhnreza/rmdhnreza.my.id/blob/08adda60b858687bdc8ec7ab0b066b0943cec564/assets/scss/grid.scss#L5-L21

Third, change `{{- block "right-sidebar" . -}}{{ end }}` to `{{ partial "sidebar/right.html" . }}` (Line 16)
https://github.com/rmdhnreza/rmdhnreza.my.id/blob/08adda60b858687bdc8ec7ab0b066b0943cec564/layouts/_default/baseof.html#L9-L19

**Comment by L-09** [comment]
非常感谢！！
